#FROM alpine:latest

FROM ubuntu:22.04

# Actualizacion de repositorios:
RUN apt update
RUN apt install apache2 -y

#docker run -it -v /home/catv/VoDServer/htdocs/:/var/www/html/ --name VoDServer --restart always vodserver
